### ISSUE TITLE
"Return Ad" should be optional

### ISSUE THREAD

**Issue by nyancodeid** [lreiner/cordova-plugin-startapp-ads#3]
The **Return Ad** is a new ad unit which is displayed once the user returns to your application after a certain period of time. To minimize the intrusiveness, short time periods are ignored.

Return ads are enabled and activated by default. If you want to disable this feature, simply pass "false" as the 3th parameter of the `StartAppSDK.init` method:

```js
StartAppSDK.init(cordova.getActivity(), "Your App ID", false);
```
This ad should be optional and pass into `init` method. 

Nice Plugin.

**Comment by lukasreiner** [comment]
fixed with ec49ffc :)
