### ISSUE TITLE
Banner view issues

### ISSUE THREAD

**Issue by nyancodeid** [lreiner/cordova-plugin-startapp-ads#5]
Banner going weird sometimes. It will jump into top or bottom. But i see on code, default is bottom view. 

I guess problem is when banner hide (set to visible GONE) and when we call showBanner it should be set visible to VISIBLE not create new one. And view should be removed all when we try to create and added Banner into parentView.

I working on this issues on my fork repository. But i still can't reproduce this error.  

https://github.com/nyancodeid/cordova-plugin-startapp-ads/tree/v1.2.1

![Banner View Issues](https://user-images.githubusercontent.com/24630806/64468400-a9ec4a00-d14e-11e9-8230-a51e29d18717.png)

**Comment by lukasreiner** [comment]
> I working on this issues on my fork repository. But i still can't reproduce this error.

Are you working with the currently version of the project? 
Can you provide an example how you implemented your banner Ad?
