### ISSUE TITLE
Reward Video Not worked

### ISSUE THREAD

**Issue by abdosaeedelhassan** [lreiner/cordova-plugin-startapp-ads#7]
Banners ads and Interstitial ads work correctly, but rewarded video not worked for me

**Comment by lukasreiner** [comment]
can you provide code snippets on how you implemented your rewarded video ads? 
Thanks

**Comment by abdosaeedelhassan** [comment]
i do the steps as follows:
1- ionic cordova plugin add https://github.com/lreiner/cordova-plugin-startapp-ads.git
2- create service and then declare var StartAppAds:any;
3-  create next functions
```
  initAds() {
    if (this.platform.is("android")) {
      StartAppAds.init("xxxxxxxxx");
    }
  }

  showBanner() {
    StartAppAds.showBanner();
  }
  hideBanner() {
    StartAppAds.hideBanner();
  }
  showInterstitial() {
    StartAppAds.showInterstitial();
  }
  showRewardVideo() {
    StartAppAds.showRewardVideo();
  }
```


4- used the service inside page after init in main app component

thanks
